"""Add rent_per_month and units to properties

Revision ID: d300fa2512e5
Revises: 
Create Date: 2024-11-26 11:43:46.484309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd300fa2512e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent_per_month', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('units', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('units')
        batch_op.drop_column('rent_per_month')

    # ### end Alembic commands ###
